version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/respriter
hooks:
  BeforeInstall:
    - location: deploy/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: deploy/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: ubuntu

