#!/bin/bash
for i in "$@"
do
case $i in
  -e=*|--environment=*)
  ENVIRONMENT="${i#*=}"
  echo $ENVIRONMENT
  shift # past argument=value
  ;;
esac
done

ENVIRONMENT=${ENVIRONMENT:-}

docker-compose run --service-ports --entrypoint /bin/bash app
