version: '3'
services:
  base.clspt: &base
    image: classpert/web-app
    env_file:
      - envs/dev/base.env
      - envs/local/base.env
    volumes:
      - .:/app
      - /app/volumes
      - base_bundle:/home/developer/bundle:cached
      - base_node_modules:/home/developer/node_modules:cached

  app.clspt:
    <<: *base
    environment:
      - VIRTUAL_HOST=app.clspt,*.app.clspt
    ports:
      - 3000
    depends_on:
      - api.clspt
      - webpacker.clspt
      - database.clspt
      - search.clspt
      - thumbor.clspt
      - assets-proxy.clspt
      - proxy.clspt
      - mail.clspt
      - video.clspt

  que.clspt:
    <<: *base
    command: bundle exec que
    depends_on:
      - database.clspt
      - mail.clspt

  ssr.clspt:
    <<: *base
    command: node ssr/hypernova.js
    environment:
      - VIRTUAL_HOST=ssr.clspt
    ports:
      - 7777
    depends_on:
      - proxy.clspt

  webpacker.clspt:
    <<: *base
    command: bin/webpack-dev-server
    environment:
      - VIRTUAL_HOST=webpacker.clspt
    ports:
      - 3035:3035
    depends_on:
      - proxy.clspt

  database.clspt:
    image: classpert/database:1.3.9
    env_file:
      - envs/dev/database.env
      - envs/local/database.env
    ports:
      - 5432:5432
    volumes:
      - .:/app
      - /app/volumes
      - database_data:/var/lib/postgresql/data
      - ./images/database/production_seed.sql:/docker-entrypoint-initdb.d/x_seed.sql
      - ./images/database/development_seed.sql:/docker-entrypoint-initdb.d/z_seed.sql

  api.clspt:
    image: postgrest/postgrest
    env_file:
      - envs/dev/api.env
      - envs/local/api.env
    environment:
      - VIRTUAL_HOST=api.clspt
    ports:
      - 3000
    depends_on:
      - database.clspt
      - proxy.clspt

  search.clspt:
    image: nshou/elasticsearch-kibana:kibana6
    environment:
      - VIRTUAL_HOST=kibana.clspt
      - VIRTUAL_PORT=5601
      - "discovery.type=single-node"
    ports:
      - 5601
      - 9200:9200
    volumes:
      - search_data:/home/elasticsearch/elasticsearch/data
    depends_on:
      - proxy.clspt

  thumbor.clspt:
    image: dalthon/thumbor-s3-storage
    env_file:
      - envs/dev/thumbor.env
      - envs/local/thumbor.env
    environment:
      - VIRTUAL_HOST=thumbor.clspt
    ports:
      - 8000
    volumes:
      - ./images/thumbor/thumbor.conf:/thumbor/thumbor.conf
    depends_on:
      - s3.clspt
      - proxy.clspt

  mail.clspt:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mail.clspt
      - VIRTUAL_PORT=1080
    ports:
      - 1080
      - 1025:1025
    depends_on:
      - proxy.clspt

  s3.clspt:
    image: vladnev/fake-s3
    command: -r /storage -p 9000 -H s3.clspt
    environment:
      - VIRTUAL_HOST=s3.clspt
    ports:
      - 9000
    volumes:
      - s3_data:/storage
    depends_on:
      - proxy.clspt

  # Think about change image to nginx:alpine
  assets-proxy.clspt:
    image: nginx
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/upload_assets.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    env_file:
      - envs/dev/assets-proxy.env
      - envs/local/assets-proxy.env
    environment:
      - VIRTUAL_HOST=assets-proxy.clspt
    ports:
      - 80
    volumes:
      - ./images/assets-proxy/upload_assets.template:/etc/nginx/conf.d/upload_assets.template
    depends_on:
      - s3.clspt
      - proxy.clspt

  user.app.clspt:
    image: classpert/user-dashboard:1.0.0
    command: run serve
    env_file:
      - envs/dev/user.env
      - envs/local/user.env
    environment:
      - VIRTUAL_HOST=user.app.clspt
    volumes:
      - ../user-dashboard:/app
    ports:
      - 8080
    depends_on:
      - app.clspt
      - api.clspt
      - proxy.clspt

  developer.app.clspt:
    image: classpert/developers-dashboard:1.0.0
    command: run serve
    env_file:
      - envs/dev/developer.env
      - envs/local/developer.env
    environment:
      - VIRTUAL_HOST=developer.app.clspt
    volumes:
      - ../developers-dashboard:/app
    ports:
      - 8080
    depends_on:
      - app.clspt
      - api.clspt
      - proxy.clspt

  database.napoleon.clspt:
    image: classpert/napoleon_database
    env_file:
      - envs/dev/database-napoleon.env
      - envs/local/database-napoleon.env
    volumes:
      - database_napoleon_data:/var/lib/postgresql/data
      - ./images/napoleon_database/seed.sql:/docker-entrypoint-initdb.d/z_seed.sql
    ports:
      - 5434:5432

  api.napoleon.clspt:
    image: postgrest/postgrest
    env_file:
      - envs/dev/api-napoleon.env
      - envs/local/api-napoleon.env
    environment:
      - VIRTUAL_HOST=api.napoleon.clspt
    ports:
      - 3000
    depends_on:
      - database.napoleon.clspt
      - proxy.clspt

  napoleon.clspt:
    entrypoint: /usr/bin/entrypoint
    image: classpert/napoleon
    command: make worker
    env_file:
      - envs/dev/napoleon.env
      - envs/local/napoleon.env
    volumes:
      - ../napoleon:/app
      - ./images/provider/www:/var/www
      - ./images/napoleon/entrypoint:/usr/bin/entrypoint
      - ./images/napoleon/update_napoleon_etc_hosts:/usr/bin/update_napoleon_etc_hosts
    depends_on:
      - database.napoleon.clspt
      - mail.clspt
      - s3.clspt

  video.clspt:
    image: classpert/video-service:minimal
    env_file:
      - envs/dev/video.env
      - envs/local/video.env
    environment:
      - VIRTUAL_HOST=video.clspt
    ports:
      - 6666

  provider.clspt:
    image: classpert/mocked_providers:latest
    build:
      context: images/provider/.
      dockerfile: Dockerfile
    environment:
      - DOMAIN=provider.clspt
      - VIRTUAL_HOST=provider.clspt,*.provider.clspt
    volumes:
      - ./images/provider/www:/var/www
    ports:
      - 80
    depends_on:
      - proxy.clspt

  proxy.clspt:
    image: classpert/nginx-proxy
    environment:
      - DEV_DOMAIN=clspt
    volumes:
      - ./images/proxy/proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 53:53/udp

  volumes.clspt:
    image: atmoz/sftp:alpine
    command: squerol:squerol123:::volumes
    volumes:
      - ./images/volumes/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./images/volumes/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - base_bundle:/home/squerol/volumes/base_bundle
      - base_node_modules:/home/squerol/volumes/base_node_modules
      - database_data:/home/squerol/volumes/database_data
      - search_data:/home/squerol/volumes/search_data
      - s3_data:/home/squerol/volumes/s3_data
    ports:
      - '2222:22'

volumes:
  base_bundle:
  base_node_modules:
  database_data:
  database_napoleon_data:
  search_data:
  s3_data:
