version: "3"
services:
  base: &base
    image: classpert/components:1.0.0
    ports:
      - "8090:8080"
    volumes:
      - .:/app

  npm_development:
    <<: *base
    env_file:
      - .env

  npm_production:
    <<: *base
    env_file:
      - .env.production
