version: "3.5"

services:
  base.clspt: &base
    image: $WEB_APP_IMAGE
    build:
      context: ./web-app
      args:
        - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
    env_file:
      - envs/dev/base.env
      - envs/local/base.env
    volumes:
      - ./web-app:/app
      - ./envs:/app/envs
      - ./i18n:/app/config/locales
      - ./components:/app/app/assets/vue/components
      - $LOCAL_NODE_MODULES/app/node_modules
      - base_bundle:/home/developer/bundle:cached
      - base_node_modules:/home/developer/node_modules:cached
    links: &sample_providers
      - provider.clspt:both.provider.clspt
      - provider.clspt:sitemaps.provider.clspt
      - provider.clspt:urls.provider.clspt

  app.clspt:
    <<: *base
    environment:
      - VIRTUAL_HOST=app.clspt,*.app.clspt
      - LOGSPOUT=ignore
    ports:
      - 3000
    depends_on:
      - api.clspt
      - webpack.clspt
      - ssr.clspt
      - database.clspt
      - memcached.clspt
      - search.clspt
      - thumbor.clspt
      - assets-proxy.clspt
      - proxy.clspt
      - mail.clspt
      - video.clspt

  que.clspt:
    <<: *base
    command: bundle exec que
    depends_on:
      - database.clspt
      - mail.clspt

  ssr.clspt:
    <<: *base
    command: make hypernova
    environment:
      - VIRTUAL_HOST=ssr.clspt
      - LOGSPOUT=ignore
    ports:
      - 7777
    depends_on:
      - proxy.clspt

  webpack.clspt:
    <<: *base
    command: npm run dev
    environment:
      - VIRTUAL_HOST=webpack.clspt
      - LOGSPOUT=ignore
    ports:
      - 3035:3035
    depends_on:
      - proxy.clspt

  database.clspt:
    image: $DATABASE_IMAGE
    build: database/.
    env_file:
      - envs/dev/database.env
      - envs/local/database.env
    environment:
      - LOGSPOUT=ignore
    ports:
      - 5432:5432
    volumes:
      - ./database:/database
      - database_data:/var/lib/postgresql/data:cached

  api.clspt:
    image: postgrest/postgrest:v6.0.2
    env_file:
      - envs/dev/api.env
      - envs/local/api.env
    environment:
      - VIRTUAL_HOST=api.clspt
      - LOGSPOUT=ignore
    ports:
      - 3000
    depends_on:
      - database.clspt
      - proxy.clspt

  search.clspt:
    image: nshou/elasticsearch-kibana:kibana6
    environment:
      - VIRTUAL_HOST=kibana.clspt
      - VIRTUAL_PORT=5601
      - LOGSPOUT=ignore
      - "discovery.type=single-node"
    ports:
      - 5601
      - 9200:9200
    volumes:
      - search_data:/home/elasticsearch/elasticsearch/data:cached
    depends_on:
      - proxy.clspt

  thumbor.clspt:
    image: dalthon/thumbor-s3-storage
    env_file:
      - envs/dev/thumbor.env
      - envs/local/thumbor.env
    environment:
      - VIRTUAL_HOST=thumbor.clspt
      - LOGSPOUT=ignore
    ports:
      - 80
    volumes:
      - ./images/thumbor/thumbor.conf:/thumbor/thumbor.conf
    depends_on:
      - s3.clspt
      - proxy.clspt

  mail.clspt:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mail.clspt
      - VIRTUAL_PORT=1080
      - LOGSPOUT=ignore
    ports:
      - 1080
      - 1025:1025
    depends_on:
      - proxy.clspt

  s3.clspt:
    image: classpert/minio
    build: images/minio/.
    command: minio server --address :80 /data
    env_file:
      - envs/dev/minio.env
      - envs/local/minio.env
    environment:
      - VIRTUAL_HOST=s3.clspt
      - LOGSPOUT=ignore
    volumes:
      - s3_data:/data:cached
    ports:
      - 80
    depends_on:
      - proxy.clspt

  assets-proxy.clspt:
    image: nginx:alpine
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/upload_assets.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    env_file:
      - envs/dev/assets-proxy.env
      - envs/local/assets-proxy.env
    environment:
      - VIRTUAL_HOST=assets-proxy.clspt
      - LOGSPOUT=ignore
    ports:
      - 80
    volumes:
      - ./images/assets-proxy/upload_assets.template:/etc/nginx/conf.d/upload_assets.template
    depends_on:
      - s3.clspt
      - proxy.clspt

  user.app.clspt:
    image: $USER_IMAGE
    build:
      context: user-dashboard/.
      dockerfile: Dockerfile
      args:
        - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
    env_file:
      - envs/dev/user.env
      - envs/local/user.env
    environment:
      - VIRTUAL_HOST=user.app.clspt
      - LOGSPOUT=ignore
    volumes:
      - ./user-dashboard:/app
      - /app/node_modules
      - ./i18n:/app/src/locales:cached
      - ./components:/app/src/components/external:cached
    ports:
      - 1080
    depends_on:
      - app.clspt
      - api.clspt
      - proxy.clspt

  developer.app.clspt:
    image: $DEVELOPER_IMAGE
    build:
      context: developers-dashboard/.
      dockerfile: Dockerfile
      args:
        - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
    env_file:
      - envs/dev/developer.env
      - envs/local/developer.env
    environment:
      - VIRTUAL_HOST=developer.app.clspt
      - LOGSPOUT=ignore
    volumes:
      - ./developers-dashboard:/app
      - /app/node_modules
      - ./i18n:/app/src/locales:cached
      - ./components:/app/src/components/external:cached
    ports:
      - 1080
    depends_on:
      - app.clspt
      - api.clspt
      - que.clspt
      - logshuttle.clspt
      - urlbox.clspt
      - proxy.clspt

  database.napoleon.clspt:
    image: $NAPOLEON_DATABASE_IMAGE
    build: ./napoleon-database
    env_file:
      - envs/dev/database-napoleon.env
      - envs/local/database-napoleon.env
    environment:
      - LOGSPOUT=ignore
    volumes:
      - ./napoleon-database:/database
      - database_napoleon_data:/var/lib/postgresql/data:cached
    ports:
      - 5434:5432

  api.napoleon.clspt:
    image: postgrest/postgrest:v6.0.2
    env_file:
      - envs/dev/api-napoleon.env
      - envs/local/api-napoleon.env
    environment:
      - VIRTUAL_HOST=api.napoleon.clspt
      - LOGSPOUT=ignore
    ports:
      - 3000
    depends_on:
      - database.napoleon.clspt
      - proxy.clspt

  napoleon.clspt:
    image: $NAPOLEON_APP_IMAGE
    build: ./napoleon
    command: make worker
    env_file:
      - envs/dev/napoleon.env
      - envs/local/napoleon.env
    environment:
      - LOGSPOUT=ignore
    volumes:
      - ./napoleon:/app
    depends_on:
      - database.napoleon.clspt
      - mail.clspt
      - s3.clspt
    links: *sample_providers

  video.clspt:
    image: classpert/video-service:minimal
    env_file:
      - envs/dev/video.env
      - envs/local/video.env
    environment:
      - VIRTUAL_HOST=video.clspt
      - LOGSPOUT=ignore
    ports:
      - 80

  provider.clspt:
    image: classpert/mocked_providers:latest
    build: images/provider/.
    environment:
      - DOMAIN=provider.clspt
      - VIRTUAL_HOST=provider.clspt,*.provider.clspt
      - LOGSPOUT=ignore
    volumes:
      - ./images/provider/www:/var/www
    ports:
      - 80
    depends_on:
      - proxy.clspt

  logdrain.clspt:
    image: classpert/log-drain:1.2.0
    environment:
      - VIRTUAL_HOST=logdrain.clspt
      - REDIS_URL=redis://redis.clspt
      - LOGSPOUT=ignore
      - ALLOWED_SOURCES=crawling-event,sitemap-verification-service,domain-validation-service,resource-discovery-service,debug-tool-service
    ports:
      - 8000
    depends_on:
      - proxy.clspt
      - redis.clspt

  logspout.clspt:
    image: gliderlabs/logspout
    environment:
      - VIRTUAL_HOST=logspout.clspt
      - LOGSPOUT=ignore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80
    depends_on:
      - proxy.clspt

  logshuttle.clspt:
    image: classpert/log-shuttle:1.2.0
    environment:
      - VIRTUAL_HOST=logshuttle.clspt
      - LOGSPOUT=ignore
      - LOGSPOUT_URL=http://logspout.clspt/logs
      - LOGPLEX_URL=http://logplex.clspt:8001
      - LOGPLEX_INPUT_URL=http://logplex.clspt:8601/logs
      - LOGDRAIN_URL=http://logdrain.clspt:8000/drain
    env_file:
      - envs/dev/logplex.env
      - envs/local/logplex.env
    depends_on:
      - logspout.clspt
      - logplex.clspt
      - logdrain.clspt

  logplex.clspt:
    image: classpert/logplex:1.0.0
    command: ./_build/default/rel/logplex/bin/logplex foreground
    hostname: logplex
    domainname: docker.local
    environment:
      - VIRTUAL_HOST=logplex.clspt
      - VIRTUAL_PORT=8001
      - LOGSPOUT=ignore
      - INSTANCE_NAME=logplex.docker.local
      - LOCAL_IP=127.0.0.1
      - LOGPLEX_CONFIG_REDIS_URL=redis://redis.clspt/
      - LOGPLEX_SHARD_URLS=redis://redis.clspt/#frag1
      - LOGPLEX_REDGRID_REDIS_URL=redis://redis.clspt/
      - LOGPLEX_STATS_REDIS_URL=redis://redis.clspt/
    env_file:
      - envs/dev/logplex.env
      - envs/local/logplex.env
    ports:
      - 8001
      - 8002:8002
      - 8601:8601
      - 6001:6001
    depends_on:
      - proxy.clspt
      - redis.clspt

  redis.clspt:
    # logplex requires this version
    image: redis:2.6
    command: redis-server
    environment:
      - VIRTUAL_HOST=redis.clspt
      - LOGSPOUT=ignore
    ports:
      - 6379
    depends_on:
      - proxy.clspt

  memcached.clspt:
    image: memcached:1.6.6-alpine
    command: memcached -m 128 -vv
    ports:
      - 11211
    depends_on:
      - proxy.clspt

  respriter.clspt:
    image: classpert/respriter:1.0.0
    command: make serve
    environment:
      - LOGSPOUT=ignore
    volumes:
      - ../respriter:/app
    ports:
      - 8080:8080
    depends_on:
      - proxy.clspt

  urlbox.clspt:
    image: classpert/screenshooter:1.3.0
    environment:
      - VIRTUAL_HOST=urlbox.clspt
      - LOGSPOUT=ignore
    ports:
      - 3566
    links:
      - provider.clspt:app.clspt
    depends_on:
      - proxy.clspt

  proxy.clspt:
    image: classpert/nginx-proxy
    environment:
      - DEV_DOMAIN=clspt
      - LOGSPOUT=ignore
    volumes:
      - ./images/proxy/proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 5300:53/udp

  volumes.clspt:
    image: atmoz/sftp:alpine
    command: squerol:squerol123:::volumes
    environment:
      - LOGSPOUT=ignore
    volumes:
      - ./images/volumes/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./images/volumes/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - base_bundle:/home/squerol/volumes/base_bundle
      - base_node_modules:/home/squerol/volumes/base_node_modules
      - database_data:/home/squerol/volumes/database_data
      - search_data:/home/squerol/volumes/search_data
      - s3_data:/home/squerol/volumes/s3_data
    ports:
      - "2222:22"

volumes:
  base_bundle:
    name: classpert_dev_base_bundle
  base_node_modules:
    name: classpert_dev_base_node_modules
  database_data:
    name: classpert_dev_database_data
  database_napoleon_data:
    name: classpert_dev_database_napoleon_data
  search_data:
    name: classpert_dev_search_data
  s3_data:
    name: classpert_dev_s3_data

networks:
  default:
    name: classpert
