production:
  s3:
    region: us-east-1

staging:
  s3:
    region: us-east-1

development:
  s3:
    region:           us-east-1
    endpoint:         http://s3.clspt/
    force_path_style: true
    ssl_verify_peer:  false

test:
  s3:
    region:           us-east-1
    endpoint:         http://s3.clspt/
    force_path_style: true
    ssl_verify_peer:  false
