version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/respriter
hooks:
  BeforeInstall:
    - location: deploy/cleanup
      timeout: 100
      runas: root
  AfterInstall:
    - location: deploy/install_dependencies
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: root
  BeforeAllowTraffic:
    - location: deploy/check_instance_health
      timeout: 10
      runas: root
