---
googlebot:
  methods:
    reverse_dns_lookup:
      - '.*googlebot\.com\z'
      - '.*google\.com\z'

yandexbot:
  methods:
    reverse_dns_lookup:
      - '.*yandex\.com\z'
      - '.*yandex\.ru\z'
      - '.*yandex\.net\z'

yahoo:
  methods:
    reverse_dns_lookup:
      - '.*crawl\.yahoo\.com\z'

bingbot:
  methods:
    reverse_dns_lookup:
      - '.*search\.msn\.com\z'

baiduspider:
  methods:
    reverse_dns_lookup:
      - '.*crawl\.baidu\.jp\z'
      - '.*crawl\.baidu\.com\z'

duckduckbot:
  methods:
    ip:
      - 23.21.227.69
      - 40.88.21.235
      - 50.16.241.113
      - 50.16.241.114
      - 50.16.241.117
      - 50.16.247.234
      - 52.204.97.54
      - 52.5.190.19
      - 54.197.234.188
      - 54.208.100.253
      - 54.208.102.37
      - 107.21.1.8
