################################### Bot inspection methods ######################################
# + Googlebot https://support.google.com/webmasters/answer/80553?hl=en                          #
# + Bingbot https://www.bing.com/webmaster/help/how-to-verify-bingbot-3905dc26                  #
# + YandexBot https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html      #
# + DuckDuckBot https://help.duckduckgo.com/duckduckgo-help-pages/results/duckduckbot/          #
#################################################################################################
---
reverse_dns_lookup:
  - '.*googlebot\.com\z'
  - '.*google\.com\z'
  - '.*yandex\.com\z'
  - '.*yandex\.ru\z'
  - '.*yandex\.net\z'
  - '.*crawl\.yahoo\.com\z'
  - '.*search\.msn\.com\z'
  - '.*crawl\.baidu\.jp\z'
  - '.*crawl\.baidu\.com\z'
ip:
  - 23.21.227.69
  - 40.88.21.235
  - 50.16.241.113
  - 50.16.241.114
  - 50.16.241.117
  - 50.16.247.234
  - 52.204.97.54
  - 52.5.190.19
  - 54.197.234.188
  - 54.208.100.253
  - 54.208.102.37
  - 107.21.1.8
