name: 'Sitemap Pipeline'
pipes:
  - type:   Fetcher
    status_map:
      - - [ 100, 199 ]
        - skipped
      - - [ 200, 399 ]
        - pending
      - - [ 400, 599 ]
        - skipped
    script: fetcher.rb
  - type:   Demux
    script: demux.rb
  - type:   Demux
    script: demux_sitemaps.rb
  - type:   Demux
    script: demux_unverified_domains.rb
