version: '3.7'

services:

  napoleon: &napoleon
    image: $NAPOLEON_APP_IMAGE
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  napoleon.clspt:
    <<: *napoleon
    env_file:
      - ../envs/dev/napoleon.env
      - ../envs/local/napoleon.env
    environment:
      - VIRTUAL_HOST=napoleon.clspt
    ports:
      - 4567
    depends_on:
      - s3.clspt
      - database.napoleon.clspt
      - proxy.clspt

  worker.napoleon.clspt:
    <<: *napoleon
    command: make worker
    env_file:
      - ../envs/dev/napoleon.env
      - ../envs/local/napoleon.env
    depends_on:
      - s3.clspt
      - mail.clspt
      - database.napoleon.clspt

  database.napoleon.clspt:
    image: $NAPOLEON_DATABASE_IMAGE
    build:
      context: ../napoleon-database
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    env_file:
      - ../envs/dev/database-napoleon.env
      - ../envs/local/database-napoleon.env
    volumes:
      - ../napoleon-database:/database
      - database_data:/var/lib/postgresql/data:cached

  api.napoleon.clspt:
    image: postgrest/postgrest:v6.0.2
    env_file:
      - ../envs/dev/api-napoleon.env
      - ../envs/local/api-napoleon.env
    environment:
      - VIRTUAL_HOST=api.napoleon.clspt
    ports:
      - 3000
    depends_on:
      - database.napoleon.clspt
      - proxy.clspt

  s3.clspt:
    image: classpert/minio
    command: minio server --address :80 /data
    env_file:
      - ../envs/dev/minio.env
      - ../envs/local/minio.env
    environment:
      - VIRTUAL_HOST=s3.clspt
    volumes:
      - s3_data:/data:cached
    ports:
      - 80
    depends_on:
      - proxy.clspt

  mail.clspt:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mail.clspt
      - VIRTUAL_PORT=1080
    ports:
      - 1080
      - 1025
    depends_on:
      - proxy.clspt

  provider.clspt:
    image: nginx:alpine
    volumes:
      - ./images/provider:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=provider.clspt
    ports:
      - 80
    depends_on:
      - proxy.clspt

  proxy.clspt:
    image: classpert/nginx-proxy
    environment:
      - DEV_DOMAIN=clspt
    volumes:
      - ./images/proxy/proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 5300:53/udp

  mitm.proxy.clspt:
    image: mitmproxy/mitmproxy
    command: mitmweb --web-iface 0.0.0.0
    environment:
      - VIRTUAL_HOST=mitm.proxy.clspt
      - VIRTUAL_PORT=8081
    ports:
      - 8080
      - 8081

  anonymous.proxy.clspt:
    image: mattes/rotating-proxy
    environment:
      - tors=25
      - VIRTUAL_HOST=anonymous.proxy.clspt
      - VIRTUAL_PORT=4444
    ports:
      - 5566 # HTTP Proxy
      - 4444 # HAproxy Stats

  napoleon.test:
    <<: *napoleon
    env_file:
      - ../envs/test/napoleon.env
    depends_on:
      - s3.clspt
      - mail.clspt
      - proxy.test
      - database.napoleon.test
      - heavyload.service.test

  database.napoleon.test:
    image: $NAPOLEON_DATABASE_IMAGE
    ports:
      - 5432
    env_file:
      - ../envs/test/database-napoleon.env
    volumes:
      - ../napoleon-database:/database

  proxy.test:
    image: classpert/napoleon_test_proxy
    build:
      context: ./images/test_proxy
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=proxy.test
    ports:
      - 8888

  heavyload.service.test:
    image: classpert/napoleon_heavyload_service
    build:
      context: ./images/heavyload_service
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=heavyload.service.test
    ports:
      - 9999

volumes:
  s3_data:
    name: classpert_napoleon_dev_s3_data
  database_data:
    name: classpert_napoleon_dev_database_data

networks:
  default:
    name: classpert
