Layout/LineLength:
  Max: 100
Style/HashEachMethods:
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
