###################################################################################################################
# + Alphabetical order                                                                                            #
# + Comments go on the right                                                                                      #
# + Comments are specially welcome when it's impossible to know what the gem does just by looking to its name     #
# + Use github shorthand when possible                                                                            #
###################################################################################################################

ruby '2.6.5'

gem 'active_record_upsert',             '~> 0.9.5'
gem 'activerecord-import',              '~> 1.0.4'  # Bulk insert for ActiveRecord
gem 'affiliate_hub',                    github: 'codextremist/affiliate_hub'
gem 'affiliate_hub_awin',               github: 'codextremist/affiliate_hub_awin'
gem 'affiliate_hub_cj',                 github: 'codextremist/affiliate_hub_cj'
gem 'affiliate_hub_impact_radius',      github: 'codextremist/affiliate_hub_impact_radius'
gem 'affiliate_hub_rakuten_marketing',  github: 'codextremist/affiliate_hub_rakuten_marketing'
gem 'affiliate_hub_shareasale',         github: 'codextremist/affiliate_hub_shareasale'
gem 'aws-sdk-cloudfront',               '~> 1.23.0'
gem 'browser',                          '~> 4.2'    # Detect browser by user agent
gem 'carrierwave',                      '~> 2.0.2'
gem 'carrierwave-aws',                  '~> 1.4.0'
gem 'cld',                              '~> 0.8.0'  # Google Chrome's Compact Language Detector for Ruby
gem 'crack',                            '~> 0.4.3'  # XML parser
gem 'dalli'
gem 'damerau-levenshtein',              '~> 1.3.2'
gem 'devise',                           '~> 4.7.1'
gem 'devise-jwt',                       '~> 0.5.8'
gem 'dnsruby',                          '~> 1.61.3'
gem 'ejs',                              '~> 1.1.1'
gem 'elasticsearch-dsl',                '~> 0.1.0'
gem 'elasticsearch-model',              '~> 6.0.0'
gem 'elasticsearch-rails',              '~> 6.0.0'
gem 'execjs',                           '~> 2.7.0'
gem 'fast_jsonapi',                     '~> 1.5'
gem 'http',                             '~> 4.2.0'
gem 'http-accept',                      '~> 2.1.1'
gem 'httparty',                         '~> 0.17.1'
gem 'hypernova',                        '~> 1.4.0'  # Ruby client for the Hypernova service (SSR of Javascript Views)
gem 'inky-rb',                          '~> 1.3.7.5', require: 'inky'
gem 'ipcat'                                         # Detect IP addresses from known datacenters
gem 'json_schemer',                     '~> 0.2.8'
gem 'kaminari',                         '~> 1.1.1'  # Pagination for Rails
gem 'kramdown',                         '~> 2.3.0'
gem 'lograge',                          '~> 0.11.2' # Make Rails default logger less verbose
gem 'mecab_standalone',                 github: "wyugue/mecab_standalone"
gem 'mini_magick',                      '~> 4.9.5'
gem 'minipack',                         '~> 0.3.5'
gem 'omniauth-facebook',                '~> 5.0.0'
gem 'omniauth-github',                  '~> 1.3.0'
gem 'omniauth-linkedin-oauth2',         '~> 1.0.0'
gem 'omniauth-oauth2',                  '~> 1.6.0'
gem 'omniauth-reddit',                  github: 'jackdempsey/omniauth-reddit'
gem 'omniauth-twitter',                 '~> 1.4.0'
gem 'parser',                           '~> 2.7.0.1', require: 'parser/current'
gem 'pg',                               '~> 1.1'
gem 'pg_query',                         '~> 1.2.0'
gem 'premailer-rails',                  '~> 1.10.3'
gem 'public_suffix',                    '~> 4.0.3'
gem 'puma',                             '~> 4.2'
gem 'que',                              github: 'que-rb/que', ref: 'c3547'
gem 'que-web'
gem 'rack-attack'
gem 'rack-cors',                        '~> 1.0.3'
gem 'rack-proxy',                       '~> 0.6.1'
gem 'rails',                            '~> 6.0.0'
gem "hiredis",                          '~> 0.6.0'
gem "redis",                            '>= 3.2.0', :require => ["redis", "redis/connection/hiredis"]
gem 'robotstxt',                        '~> 0.5.4'  # A robots.txt file parser
gem 'ruby-thumbor',                     '~> 3.0.0'
gem 'semantic',                         '~> 1.6.1'
gem 'sendgrid-ruby'
gem 'sentry-raven',                     '~> 2.12.2',  group: :production
gem 'sitemap_generator',                '~> 6.0.2'
gem 'unparser',                         '~> 0.4.7'
gem 'user_agent_parser',                '~> 2.6.0'
gem 'valid_email2',                     '~> 3.1.0'
gem 'vueonrails',                       '~> 1.x'

group :test do
  gem 'capybara'
  gem 'capybara-email'
  gem 'cucumber-rails',                 require: false
  gem 'database_cleaner'
  gem 'fivemat'
  gem 'guard-rspec'
  gem 'rspec-mocks'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'simplecov',                      require: false
  gem 'vcr'
  gem 'webmock'
end

group :development, :test do
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'rubocop',                        '~> 0.80.1',  require: false
  gem 'spring'
end
