#!/bin/bash
. /home/ubuntu/.profile
sudo chown -R ubuntu:ubuntu /home/ubuntu/respriter
cd /home/ubuntu/respriter
bundle install
npm install
# initial setup for a fresh start
export SPRITE_VERSION=$(node -p "require('./package.json').elements.version")
export SPRITE_FILES=https://your.assets.cdn.com/sprites.svg
./bin/build --sprite-version=$SPRITE_VERSION --sprite-files=$SPRITE_FILES
