version: '3.7'

services:
  migrator:
    image: migrator
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_ENV: development
    env_file:
      - ../envs/dev/database.env

  database.clspt:
    image: postgres:11.4-alpine
    env_file:
      - ../envs/dev/database.env
    ports:
      - 5432:5432
