version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make
    image: classpert/video-service:latest
    env_file: .env
    volumes:
      - .:/go/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
