FROM classpert/video-service AS builder

COPY . .

RUN dep ensure && make compile

CMD ["make"]

FROM alpine

WORKDIR /app

RUN apk update                         && \
    apk upgrade                        && \
    apk add --no-cache ca-certificates && \
    update-ca-certificates 2>/dev/null || true

COPY --from=builder /go/src/app/app ./

ENTRYPOINT ["./app"]
