- { id: 'arts_and_design',                  icon: 'rule-and-pencil' }
- { id: 'business',                         icon: 'business' }
- { id: 'marketing',                        icon: 'target' }
- { id: 'computer_science',                 icon: 'card' }
- { id: 'data_science',                     icon: 'data' }
- { id: 'language_and_communication',       icon: 'dialog' }
- { id: 'life_sciences',                    icon: 'atom' }
- { id: 'math_and_logic',                   icon: 'categories' }
- { id: 'personal_development',             icon: 'graph' }
- { id: 'physical_science_and_engineering', icon: 'gear' }
- { id: 'social_science',                   icon: 'user' }
- { id: 'health_and_fitness',               icon: 'cross' }
