- {
    id: 'computer_science',
    icon: 'card'
  }
- {
    id: 'arts_and_design',
    icon: 'rule-and-pencil'
  }
- {
    id: 'business',
    icon: 'business'
  }
- {
    id: 'personal_development',
    icon: 'graph'
  }
- {
    id: 'data_science',
    icon: 'data'
  }
- {
    id: 'physical_science_and_engineering',
    icon: 'gear'
  }
- {
    id: 'marketing',
    icon: 'target'
  }
- {
    id: 'language_and_communication',
    icon: 'dialog'
  }
- {
    id: 'life_sciences',
    icon: 'atom'
  }
- {
    id: 'math_and_logic',
    icon: 'categories'
  }
- {
    id: 'social_sciences',
    icon: 'user'
  }
- {
    id: 'health_and_fitness',
    icon: 'cross'
  }
