CREATE TABLE app.courses (
  id                                      uuid                    DEFAULT public.uuid_generate_v4() PRIMARY KEY,
  global_sequence                         integer,
  name                                    varchar,
  description                             text,
  slug                                    varchar,
  url                                     varchar,
  url_md5                                 varchar,
  duration_in_hours                       numeric,
  price                                   numeric,
  rating                                  numeric,
  relevance                               integer                 DEFAULT 0,
  region                                  varchar,
  audio                                   text[]                  DEFAULT '{}',
  subtitles                               text[]                  DEFAULT '{}',
  published                               boolean                 DEFAULT true,
  stale                                   boolean                 DEFAULT false,
  category                                app.category,
  provider_id                             uuid                    REFERENCES app.providers(id),
  created_at                              timestamptz             DEFAULT NOW() NOT NULL,
  updated_at                              timestamptz             DEFAULT NOW() NOT NULL,
  dataset_sequence                        integer,
  resource_sequence                       integer,
  tags                                    text[]                  DEFAULT '{}',
  video                                   jsonb,
  source                                  app.source              DEFAULT 'api',
  pace                                    app.pace,
  certificate                             jsonb                   DEFAULT '{}',
  pricing_models                          jsonb                   DEFAULT '[]',
  offered_by                              jsonb                   DEFAULT '[]',
  syllabus                                text,
  effort                                  integer,
  enrollments_count                       integer                 DEFAULT 0,
  free_content                            boolean                 DEFAULT false,
  paid_content                            boolean                 DEFAULT true,
  level                                   app.level[]             DEFAULT '{}',
  __provider_name__                       varchar,
  __source_schema__                       jsonb,
  instructors                             jsonb                   DEFAULT '[]',
  curated_tags                            varchar[]               DEFAULT '{}',
  refinement_tags                         varchar[],
  up_to_date_id                           uuid                    REFERENCES app.courses(id) ON DELETE SET NULL,
  last_execution_id                       uuid,
  schema_version                          varchar,
  locale                                  app.locale,
  locale_status                           app.locale_status,
  ignore_robots_noindex_rule_for          app.locale[]            DEFAULT '{}',
  ignore_robots_noindex_rule              boolean                 DEFAULT false,
  canonical_subdomain                     varchar,
  course_category_id                      uuid                    REFERENCES app.course_categories(id) ON DELETE SET NULL
);
