CREATE TABLE app.preview_courses (
  id                  uuid                      DEFAULT    public.uuid_generate_v1() PRIMARY KEY,
  status              app.preview_course_status DEFAULT    'pending',
  name                varchar,
  description         text,
  slug                varchar,
  url                 varchar       NOT NULL,
  url_md5             varchar,
  duration_in_hours   numeric,
  price               numeric,
  rating              numeric,
  relevance           integer       DEFAULT 0,
  region              varchar,
  audio               text[]        DEFAULT '{}'::text[],
  subtitles           text[]        DEFAULT '{}'::text[],
  published           boolean       DEFAULT true,
  stale               boolean       DEFAULT false,
  category            app.category,
  tags                text[]        DEFAULT '{}'::text[],
  video               jsonb,
  source              app.source    DEFAULT 'api'::app.source,
  pace                app.pace,
  certificate         jsonb         DEFAULT '{}'::jsonb,
  pricing_models      jsonb         DEFAULT '[]'::jsonb,
  offered_by          jsonb         DEFAULT '[]'::jsonb,
  syllabus            text,
  effort              integer,
  enrollments_count   integer       DEFAULT 0,
  free_content        boolean       DEFAULT false,
  paid_content        boolean       DEFAULT true,
  level               app.level[]   DEFAULT '{}'::app.level[],
  __provider_name__   varchar,
  __source_schema__   jsonb,
  __indexed_json__    jsonb,
  instructors         jsonb         DEFAULT '[]'::jsonb,
  curated_tags        varchar[]     DEFAULT '{}'::varchar[],
  refinement_tags     varchar[],
  provider_id         uuid          REFERENCES app.providers(id),
  provider_crawler_id uuid          REFERENCES app.provider_crawlers(id)     ON DELETE CASCADE,
  created_at          timestamptz   DEFAULT    NOW()                         NOT NULL,
  updated_at          timestamptz   DEFAULT    NOW()                         NOT NULL,
  expired_at          timestamptz   DEFAULT    NOW() + INTERVAL '20 MINUTES' NOT NULL
);
