#!/bin/bash
for i in "$@"
do
case $i in
  -e=*|--environment=*)
  ENVIRONMENT="${i#*=}"
  echo "--------- $ENVIRONMENT environment ---------"
  shift # past argument=value
  ;;
esac
done

ENVIRONMENT=${ENVIRONMENT:-development}

docker-compose -f "../docker-compose.$ENVIRONMENT.yml" run --service-ports --entrypoint /bin/bash app
