CREATE USER grafana WITH PASSWORD '$GRAFANA_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRES_DB    TO "grafana";
GRANT USAGE   ON SCHEMA app               TO "grafana";
GRANT SELECT  ON ALL TABLES IN SCHEMA app TO "grafana";
