CREATE USER stitch WITH PASSWORD '$STITCHDATA_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRES_DB    TO "stitch";
GRANT CREATE  ON DATABASE $POSTGRES_DB    TO "stitch";
GRANT CREATE  ON SCHEMA bi                TO "stitch";
GRANT USAGE   ON SCHEMA bi                TO "stitch";
